name: 🌋 Acceso a la Fortaleza Prohibida

on: push

jobs:
  acceso-a-la-base:
    runs-on: ubuntu-latest
    steps:
        - name: "El agente llega a la fortaleza"
          run: |
                echo "El agente ${{github.actor}} llega a la fortaleza prohibida"
                echo ""
                echo "Buscar los archivos de la Legion"
                ls -la
                echo ""
                echo "❌ pero que paso? no hay nada"
        - name: "Brainiac desbloquea la boveda"
          uses: actions/checkout@v4
        
        - name: "Ahora si vamos a ver los planes"
          run: |
                echo "Buscar los archivos de la Legion"
                ls -la
                echo "✅ Funciona!!!"
                echo ""
                echo "Planes:"
                echo ls planes/
                echo ""
                echo "Villanos:"
                echo ls villanos/
                echo ""
                echo "Inteligencia:"
                echo ls inteligencia/

                
            
            